[project]
name = "earth616-ontology"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pylode>=3.2.1",
    "pyshacl>=0.30.1",
    "pytest>=8.3.5",
    "rdflib>=7.1.4",
]
