[project]
name = "earth616-ontology"
version = "0.3.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyshacl>=0.29.0",
    "rdflib>=7.1.1",
    "termcolor>=2.5.0",
]
