# Local development environment configuration
environment: local

# Persistent URI bases (what external clients use)
uri_bases:
  context: "https://vocab.earth616.localhost/context"
  ontology: "https://vocab.earth616.localhost/ont" 
  shapes: "https://vocab.earth616.localhost/shapes"
  rules: "https://vocab.earth616.localhost/rules"
  data: "https://vocab.earth616.localhost/data"

# Deployment bases (where files are actually served from)
deployment_bases:
  context: "http://localhost:8080/release/contexts/latest"
  ontology: "http://localhost:8080/release/ontology/latest"
  shapes: "http://localhost:8080/release/shapes/latest" 
  rules: "http://localhost:8080/release/rules/latest"
  data: "http://localhost:8080/release/data/latest"

# Template variable mappings for envsubst
CONTEXT_BASE: "https://vocab.earth616.localhost/context"
ONTOLOGY_BASE: "https://vocab.earth616.localhost/ont"
SHAPES_BASE: "https://vocab.earth616.localhost/shapes"
RULES_BASE: "https://vocab.earth616.localhost/rules"
DATA_BASE: "https://vocab.earth616.localhost/data"

# Version information
version: "0.2.0"